[emqtt]
debug = true #启用框架自动调试日志
brokers = ["tcp://mqtt-z9.zhizhongbao.cn:1883"]
username = "soe"
password = "88951566"
ClientID= "z9test-luc"

[emqtt.subscribeTopics.s1]
topic = "z9_8b070ac409c920da"
qos = 0

[emqtt.subscribeTopics.s2]
topic = "topic2"
qos = 1
