[emqtt]
debug = true #启用框架自动调试日志
brokers = ["tcp://emqtt.soe.xin:1883"]
username = "soe"
password = "88951566"
ClientID= "test-luc"

[emqtt.subscribeTopics.s1]
topic = "topic1"
qos = 1

[emqtt.subscribeTopics.s2]
topic = "topic2"
qos = 1
