[redis.test]
   debug = true # ego增加redis debug，打开后可以看到，配置名、地址、耗时、请求数据、响应数据
   addr = "127.0.0.1:6379"
   enableAccessInterceptor = true
   enableAccessInterceptorReq = true
   enableAccessInterceptorRes = true
